services:
  postgres:
      image: postgres:15
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: messenger_db
      networks:
        - dev
  messenger_frontend:
    build:
      context: ./frontend 
    networks:
      - dev

  messenger_backend:
    build:
      context: ./backend
    command: ["/wait-for-it.sh", "postgres:5432", "--", "./messenger-backend"]
    env_file:
    - ./backend/.env
    networks:
      - dev
    depends_on:
      - postgres

networks:
  dev:
