version: '3.8'

services:
  messenger_frontend:
    build:
      context: ./frontend  # путь до папки с фронтом
    container_name: messenger_frontend
    expose:
      - "3001"  # порт, на котором работает фронт внутри сети
    environment:
      - VITE_API_URL=/messenger/api  # если используется Vite
    networks:
      - dev

  messenger_backend:
    build:
      context: ./backend  # путь до папки с backend'ом
    container_name: messenger_backend
    expose:
      - "8001"
    environment:
      - PORT=8001
      # Добавьте другие переменные, если нужно, напр. DB_URL и т.п.
    networks:
      - dev

networks:
  dev:
    external: true
