services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
      - backend
    networks:
      - dev
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger_user_db
    networks:
      - dev
        
  frontend:
    build:
      context: ./frontend 
    networks:
      - dev

  backend:
    build:
      context: ./backend
    command: ["/wait-for-it.sh", "postgres:5432", "--", "./messenger-backend"]
    ports:
      - "8080:8080"
    env_file:
    - ./backend/.env
    networks:
      - dev
    depends_on:
      - postgres
      - bot
  
  bot:
    build:
      context: ./bot
    env_file:
    - ./bot/.env
    ports:
      - "8085:8085"
    networks:
      - dev

networks:
  dev:
