services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      -  frontend-dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - dev
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger_db
    networks:
      - dev
        
  frontend:
    build:
      context: ./frontend 
    volumes:
      - frontend-dist:/app/dist
    networks:
      - dev

  backend:
    build:
      context: ./backend
    command: ["/wait-for-it.sh", "postgres:5432", "--", "./messenger-backend"]
    env_file:
    - ./backend/.env
    networks:
      - dev
    depends_on:
      - postgres

networks:
  dev:
